/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alpha.c"
#include "bar_alternativetags.c"
#include "bar_anybar.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statusbutton.c"
#include "bar_winicon.c"
#include "bar_tabgroups.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_flexwintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "aspectresize.c"
#include "attachx.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "dragcfact.c"
#include "moveresize.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "renamed_scratchpads.c"
#include "sizehints_ruled.c"
#include "tapresize.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "xrdb.c"
#include "dragmfact.c"
/* Layouts */
#include "layout_flextile-deluxe.c"

