/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alpha.h"
#include "bar_alternativetags.h"
#include "bar_anybar.h"
#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statusbutton.h"
#include "bar_winicon.h"
#include "bar_tabgroups.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_wintitle.h"
#include "bar_flexwintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "aspectresize.h"
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "moveresize.h"
#include "nomodbuttons.h"
#include "pertag.h"
#include "placemouse.h"
#include "renamed_scratchpads.h"
#include "sizehints_ruled.h"
#include "tapresize.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "xrdb.h"
/* Layouts */
#include "layout_flextile-deluxe.h"

